@startmindmap
* 接口分类
** 对外接口
*** 数据展示服务
**** 区块数据展示接口
**** 交易分析接口
*** 市场风险服务
**** 市场风险查询接口
**** 风险触发记录接口
** 内部接口
*** 区块索引服务
**** 区块同步接口
**** 交易同步接口
*** 风险关联服务
**** 查询关联关系接口
** 依赖接口
*** 合约代码编译器
**** 合约编译接口
**** 合约验证接口
*** 模拟交易服务
**** 模拟交易接口
**** 手动创建交易接口
**** 机器人生成交易列表接口
*** 区块链网络
**** 信标链同步接口
**** 执行层同步接口
@endmindmap
